if test -f "$HOME/.local/share/omarchy/default/bash/envs"
    source "$HOME/.local/share/omarchy/default/bash/envs"
end

complete -c omarchy-battery-capacity -f
complete -c omarchy-battery-monitor -f
complete -c omarchy-battery-present -f
complete -c omarchy-battery-remaining -f
complete -c omarchy-battery-remaining-time -f
complete -c omarchy-battery-status -f
complete -c omarchy-branch-set -f
complete -c omarchy-brightness-display -f
complete -c omarchy-brightness-display-apple -f
complete -c omarchy-brightness-keyboard -f
complete -c omarchy-channel-set -f
complete -c omarchy-cmd-audio-switch -f
complete -c omarchy-cmd-first-run -f
complete -c omarchy-cmd-missing -f
complete -c omarchy-cmd-present -f
complete -c omarchy-cmd-screenrecord -f
complete -c omarchy-cmd-screensaver -f
complete -c omarchy-cmd-screenshot -f
complete -c omarchy-cmd-share -f
complete -c omarchy-cmd-terminal-cwd -f
complete -c omarchy-config-direct-boot -f
complete -c omarchy-debug -f
complete -c omarchy-dev-add-migration -f
complete -c omarchy-dictate -f
complete -c omarchy-drive-info -f
complete -c omarchy-drive-select -f
complete -c omarchy-drive-set-password -f
complete -c omarchy-fix-workspace-visibility -f
complete -c omarchy-font-current -f
complete -c omarchy-font-list -f
complete -c omarchy-font-set -f
complete -c omarchy-haptic-touchpad -f
complete -c omarchy-hibernation-available -f
complete -c omarchy-hibernation-remove -f
complete -c omarchy-hibernation-setup -f
complete -c omarchy-hook -f
complete -c omarchy-hw-asus-rog -f
complete -c omarchy-hw-framework16 -f
complete -c omarchy-hw-intel -f
complete -c omarchy-hw-intel-ptl -f
complete -c omarchy-hw-match -f
complete -c omarchy-hw-surface -f
complete -c omarchy-hw-vulkan -f
complete -c omarchy-hyprland-active-window-transparency-toggle -f
complete -c omarchy-hyprland-monitor-internal-toggle -f
complete -c omarchy-hyprland-monitor-scaling-cycle -f
complete -c omarchy-hyprland-window-close-all -f
complete -c omarchy-hyprland-window-gaps-toggle -f
complete -c omarchy-hyprland-window-pop -f
complete -c omarchy-hyprland-window-single-square-aspect-toggle -f
complete -c omarchy-hyprland-workspace-layout-toggle -f
complete -c omarchy-install-chromium-google-account -f
complete -c omarchy-install-dev-env -f
complete -c omarchy-install-docker-dbs -f
complete -c omarchy-install-dropbox -f
complete -c omarchy-install-geforce-now -f
complete -c omarchy-install-nordvpn -f
complete -c omarchy-install-once -f
complete -c omarchy-install-steam -f
complete -c omarchy-install-tailscale -f
complete -c omarchy-install-terminal -f
complete -c omarchy-install-vscode -f
complete -c omarchy-install-xbox-controllers -f
complete -c omarchy-launch-about -f
complete -c omarchy-launch-audio -f
complete -c omarchy-launch-bluetooth -f
complete -c omarchy-launch-browser -f
complete -c omarchy-launch-editor -f
complete -c omarchy-launch-floating-terminal-with-presentation -f
complete -c omarchy-launch-or-focus -f
complete -c omarchy-launch-or-focus-tui -f
complete -c omarchy-launch-or-focus-webapp -f
complete -c omarchy-launch-screensaver -f
complete -c omarchy-launch-tui -f
complete -c omarchy-launch-walker -f
complete -c omarchy-launch-webapp -f
complete -c omarchy-launch-wifi -f
complete -c omarchy-lock-screen -f
complete -c omarchy-menu -f
complete -c omarchy-menu-keybindings -f
complete -c omarchy-migrate -f
complete -c omarchy-notification-dismiss -f
complete -c omarchy-npx-install -f
complete -c omarchy-nvim-setup -f
complete -c omarchy-pkg-add -f
complete -c omarchy-pkg-aur-accessible -f
complete -c omarchy-pkg-aur-add -f
complete -c omarchy-pkg-aur-install -f
complete -c omarchy-pkg-drop -f
complete -c omarchy-pkg-install -f
complete -c omarchy-pkg-missing -f
complete -c omarchy-pkg-present -f
complete -c omarchy-pkg-remove -f
complete -c omarchy-powerprofiles-list -f
complete -c omarchy-refresh-applications -f
complete -c omarchy-refresh-chromium -f
complete -c omarchy-refresh-config -f
complete -c omarchy-refresh-fastfetch -f
complete -c omarchy-refresh-hypridle -f
complete -c omarchy-refresh-hyprland -f
complete -c omarchy-refresh-hyprlock -f
complete -c omarchy-refresh-hyprsunset -f
complete -c omarchy-refresh-limine -f
complete -c omarchy-refresh-pacman -f
complete -c omarchy-refresh-plymouth -f
complete -c omarchy-refresh-sddm -f
complete -c omarchy-refresh-swayosd -f
complete -c omarchy-refresh-tmux -f
complete -c omarchy-refresh-walker -f
complete -c omarchy-refresh-waybar -f
complete -c omarchy-reinstall -f
complete -c omarchy-reinstall-configs -f
complete -c omarchy-reinstall-git -f
complete -c omarchy-reinstall-pkgs -f
complete -c omarchy-remove-dev-env -f
complete -c omarchy-remove-preinstalls -f
complete -c omarchy-restart-app -f
complete -c omarchy-restart-bluetooth -f
complete -c omarchy-restart-btop -f
complete -c omarchy-restart-hyprctl -f
complete -c omarchy-restart-hypridle -f
complete -c omarchy-restart-hyprsunset -f
complete -c omarchy-restart-makima -f
complete -c omarchy-restart-mako -f
complete -c omarchy-restart-opencode -f
complete -c omarchy-restart-pipewire -f
complete -c omarchy-restart-swayosd -f
complete -c omarchy-restart-terminal -f
complete -c omarchy-restart-tmux -f
complete -c omarchy-restart-trackpad -f
complete -c omarchy-restart-walker -f
complete -c omarchy-restart-waybar -f
complete -c omarchy-restart-wifi -f
complete -c omarchy-restart-xcompose -f
complete -c omarchy-setup-dns -f
complete -c omarchy-setup-fido2 -f
complete -c omarchy-setup-fingerprint -f
complete -c omarchy-setup-makima -f
complete -c omarchy-show-done -f
complete -c omarchy-show-logo -f
complete -c omarchy-snapshot -f
complete -c omarchy-state -f
complete -c omarchy-sudo-keepalive -f
complete -c omarchy-sudo-passwordless-toggle -f
complete -c omarchy-sudo-reset -f
complete -c omarchy-swayosd-brightness -f
complete -c omarchy-swayosd-kbd-brightness -f
complete -c omarchy-system-logout -f
complete -c omarchy-system-reboot -f
complete -c omarchy-system-shutdown -f
complete -c omarchy-theme-bg-install -f
complete -c omarchy-theme-bg-next -f
complete -c omarchy-theme-bg-set -f
complete -c omarchy-theme-current -f
complete -c omarchy-theme-install -f
complete -c omarchy-theme-list -f
complete -c omarchy-theme-refresh -f
complete -c omarchy-theme-remove -f
complete -c omarchy-theme-set -f
complete -c omarchy-theme-set-browser -f
complete -c omarchy-theme-set-gnome -f
complete -c omarchy-theme-set-keyboard -f
complete -c omarchy-theme-set-keyboard-asus-rog -f
complete -c omarchy-theme-set-keyboard-f16 -f
complete -c omarchy-theme-set-obsidian -f
complete -c omarchy-theme-set-templates -f
complete -c omarchy-theme-set-vscode -f
complete -c omarchy-theme-update -f
complete -c omarchy-toggle-hybrid-gpu -f
complete -c omarchy-toggle-idle -f
complete -c omarchy-toggle-nightlight -f
complete -c omarchy-toggle-notification-silencing -f
complete -c omarchy-toggle-screensaver -f
complete -c omarchy-toggle-suspend -f
complete -c omarchy-toggle-waybar -f
complete -c omarchy-tui-install -f
complete -c omarchy-tui-remove -f
complete -c omarchy-tui-remove-all -f
complete -c omarchy-tz-select -f
complete -c omarchy-update -f
complete -c omarchy-update-analyze-logs -f
complete -c omarchy-update-antigravity -f
complete -c omarchy-update-aur-pkgs -f
complete -c omarchy-update-available -f
complete -c omarchy-update-available-reset -f
complete -c omarchy-update-branch -f
complete -c omarchy-update-calibre -f
complete -c omarchy-update-confirm -f
complete -c omarchy-update-firmware -f
complete -c omarchy-update-git -f
complete -c omarchy-update-keyring -f
complete -c omarchy-update-orphan-pkgs -f
complete -c omarchy-update-perform -f
complete -c omarchy-update-restart -f
complete -c omarchy-update-system-pkgs -f
complete -c omarchy-update-time -f
complete -c omarchy-update-without-idle -f
complete -c omarchy-upload-log -f
complete -c omarchy-version -f
complete -c omarchy-version-branch -f
complete -c omarchy-version-channel -f
complete -c omarchy-version-pkgs -f
complete -c omarchy-voxtype-config -f
complete -c omarchy-voxtype-install -f
complete -c omarchy-voxtype-model -f
complete -c omarchy-voxtype-remove -f
complete -c omarchy-voxtype-status -f
complete -c omarchy-webapp-handler-hey -f
complete -c omarchy-webapp-handler-zoom -f
complete -c omarchy-webapp-install -f
complete -c omarchy-webapp-remove -f
complete -c omarchy-webapp-remove-all -f
complete -c omarchy-wifi-powersave -f
complete -c omarchy-windows-vm -f
complete -c sudo
